version: "3.9"  # optional since v1.27.0
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: webapp:2.0
    ports:
      - "5000:80"
    restart: always
    networks:
      - webnet
networks:
  webnet: 
    # volumes:
    #   - .:/code
    #   - logvolume01:/var/log
    # links:
    #   - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}