name: Test

on:
  # Allows running your workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Contains a single job called "test"
  test:
    # runs-on: ubuntu-4g-vd52c-runner-8jzsp
    runs-on: [ubuntu-4g]
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - name: Display text
        run: echo Github self-hosted runner working
  package-check:
    runs-on: [ubuntu-4g]
    steps:
      - name: check python version
        run: python --version
      - name: check node version
        run: node --version
      - name: check java --version
        uses: actions/setup-java@v4.0.0
        
